spring.application.name=descriptAI-backend
# application.properties
server.port=8081

# MongoDB Configuration - Using Environment Variables
spring.data.mongodb.uri=${MONGODB_URI}
# Product fetch from dummyJson
external.api.url=${EXTERNAL_API_URL}
#AI api configuration -- using env variables
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}
groq.api.key=${GROQ_API_KEY}
groq.api.url=${GROQ_API_URL}

#Which AI Api will run
ai.provider=${AI_CLIENT}

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.root=INFO
logging.level.com.describeai=DEBUG